# Generated by Django 3.2.3 on 2021-05-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analogs', '0004_auto_20210529_1230'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.AddField(
            model_name='notification',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analogs.analogsset'),
        ),
    ]
