# Generated by Django 3.2.3 on 2021-05-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210529_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='set',
            new_name='analogs',
        ),
    ]
