# Generated by Django 3.2.3 on 2021-05-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_set_notification_analogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
