# Generated by Django 3.2.3 on 2021-05-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210529_1414'),
        ('analogs', '0004_auto_20210529_1230'),
        ('notification', '0006_rename_analogs_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='timenotification',
            name='celery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_notifications', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analogs.analogproduct'),
        ),
    ]
