# Generated by Django 3.2.3 on 2021-05-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analogs', '0004_auto_20210529_1230'),
        ('notification', '0007_auto_20210529_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analogs.analogproduct'),
        ),
    ]
