# Generated by Django 3.2.3 on 2021-05-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210529_1414'),
        ('analogs', '0004_auto_20210529_1230'),
        ('notification', '0008_alter_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analogs.analogproduct'),
        ),
        migrations.AlterField(
            model_name='timenotification',
            name='celery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
