# Generated by Django 3.2.3 on 2021-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210528_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('basket', 'В корзине'), ('purchased', 'Куплено')], max_length=16, null=True),
        ),
    ]
