# Generated by Django 3.2.3 on 2021-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('basket', 'В корзине'), ('purchased', 'Куплено')], default='basket', max_length=16),
        ),
    ]
