# Generated by Django 3.2.3 on 2021-05-29 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210528_2336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analogs', '0002_auto_20210529_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogproduct',
            name='type',
            field=models.CharField(choices=[('inactive', 'Неактивен'), ('selected', 'Выбран'), ('unselected', 'Невыбран')], default='inactive', max_length=16),
        ),
        migrations.AlterField(
            model_name='analogsset',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogs_sets', to='catalog.order'),
        ),
        migrations.AlterField(
            model_name='analogsset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogs_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
