# Generated by Django 3.2.3 on 2021-05-29 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210528_2336'),
        ('analogs', '0003_auto_20210529_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogproduct',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='analogproduct',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='analogproduct',
            name='number_of_times',
        ),
        migrations.RemoveField(
            model_name='analogproduct',
            name='pieces_at_time',
        ),
        migrations.RemoveField(
            model_name='analogproduct',
            name='reception_time',
        ),
        migrations.RemoveField(
            model_name='analogproduct',
            name='text',
        ),
        migrations.AddField(
            model_name='analogsset',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Продолжительность дней приёма'),
        ),
        migrations.AddField(
            model_name='analogsset',
            name='dosage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='analogsset',
            name='number_of_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колличество в день'),
        ),
        migrations.AddField(
            model_name='analogsset',
            name='reception_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogs_sets', to='catalog.applicationmethod', verbose_name='Способ приёма'),
        ),
        migrations.AddField(
            model_name='analogsset',
            name='reception_time',
            field=models.CharField(choices=[('before_eating', 'До еды'), ('after_eating', 'После еды'), ('while_eating', 'Во время'), ('empty_stomach', 'На тощак'), ('at_any', 'В любое')], default='at_any', max_length=16, verbose_name='В зависимости от еды'),
        ),
        migrations.AddField(
            model_name='analogsset',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnalogProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('analog_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analogs.analogsset')),
            ],
        ),
    ]
